//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class user
    {
        public int id { get; set; }
        [Display(Name = "First Name")]
        public string firstname { get; set; }
        [Display(Name = "Last Name")]
        public string lastname { get; set; }
        [Display(Name = "User Name")] 
        public string username { get; set; }
        [Display(Name = "Password")]
        public string password { get; set; }
    }
}
